In [1]:
import numpy 
a = [2,3,5,4,1,2,3,3,3,2,4 ,6,5,5,3,6,6]
x = numpy.mean(a)
# x = numpy.mode(a)
print(x)

3.7058823529411766


In [2]:
import numpy 
a = [2,3,5,4,1,2,3,3,3,2,4,6,5,5,3,6,6]
from scipy import stats
x = stats.mode(a)
print(x)

ModeResult(mode=array([3]), count=array([5]))


In [9]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
data = [[12,np.nan,34],[10,12,np.nan],[np.nan,11,20]]
imputer = imputer.fit(data)
data = imputer.transform(data)
print(data)



[[12.  11.5 34. ]
 [10.  12.  27. ]
 [11.  11.  20. ]]


In [11]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mode')
data = [[12,np.nan,34],[10,12,np.nan],[np.nan,11,20]]
imputer = imputer.fit(data)
data = imputer.transform(data)
print(data)


ValueError: Can only use these strategies: ['mean', 'median', 'most_frequent', 'constant']  got strategy=mode

In [10]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
data = [[12,np.nan,34],[10,12,np.nan],[np.nan,11,20]]
imputer = imputer.fit(data)
data = imputer.transform(data)
print(data)


[[12. 11. 34.]
 [10. 12. 20.]
 [10. 11. 20.]]


In [ ]:
import numpy as np
 
# Importing the SimpleImputer class. 
from sklearn.impute import SimpleImputer
 
# Imputer object using the mean strategy and
# missing_values type for imputation
imputer = SimpleImputer(missing_values = np.nan,
                        strategy ='mean')
 
data = [[12, np.nan, 34], [10, 32, np.nan],
        [np.nan, 11, 20]]
 
print("Original Data : \n", data)
# Fitting the data to the imputer object
imputer = imputer.fit(data)
 
# Imputing the data    
data = imputer.transform(data)
 
print("Imputed Data : \n", data)
# From Get Excelsior to Everyone 08:41 PM
import numpy as np
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='median')
imp_mean.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
SimpleImputer()
X = [[np.nan, 2, 3], [4, np.nan, 6], [10, 5, 9]]
print(imp_mean.transform(X))
one_hot_encoded_data = pd.get_dummies(data, columns = ['state'])
print(one_hot_encoded_data)
