In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [69]:
df = pd.read_csv("hiring.csv")
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [70]:
df["experience"].fillna('zero',inplace = True)

In [71]:
# df["experience"].replace(['five', 'two', 'seven', 'three', 'ten', 'eleven'],[5,2,7,3,10,11],inplace = True)

In [72]:
df["experience"].unique()

array(['zero', 'five', 'two', 'seven', 'three', 'ten', 'eleven'],
      dtype=object)

In [73]:
!pip install word2number

In [27]:
from word2number import w2n

In [74]:
list1 = []
for x in df["experience"]:
    a = w2n.word_to_num(x)
    list1.append(a)
print(list1)

[0, 0, 5, 2, 7, 3, 10, 11]


In [75]:
df["experience"] = list1

In [63]:
df

experience test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                   8.0                           9      50000
1           0                   8.0                           6      45000
2           5                   6.0                           7      60000
3           2                  10.0                          10      65000
4           7                   9.0                           6      70000
5           3                   7.0                          10      62000
6          10                  zero                           7      72000
7          11                   7.0                           8      80000

In [ ]:
import numpy as np
>>> from sklearn.impute import SimpleImputer
>>> imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
>>> imp_mean.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
SimpleImputer()
>>> X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
>>> print(imp_mean.transform(X))

In [76]:
from sklearn.impute import SimpleImputer

In [77]:
imputer = SimpleImputer(missing_values = np.nan,strategy = "mean")

In [78]:
imputer.fit(df[["test_score(out of 10)"]])

SimpleImputer()

In [85]:
df["test_score(out of 10)"] = imputer.transform(df[["test_score(out of 10)"]])

In [88]:
df["test_score(out of 10)"].astype("int")

0     8
1     8
2     6
3    10
4     9
5     7
6     7
7     7
Name: test_score(out of 10), dtype: int32

In [89]:
from sklearn.model_selection import train_test_split

In [90]:
from sklearn.linear_model import LinearRegression


In [91]:
model = LinearRegression()

In [92]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0               8.000000                           9      50000
1           0               8.000000                           6      45000
2           5               6.000000                           7      60000
3           2              10.000000                          10      65000
4           7               9.000000                           6      70000
5           3               7.000000                          10      62000
6          10               7.857143                           7      72000
7          11               7.000000                           8      80000

In [99]:
x_train,x_test,y_train,y_test = train_test_split(df[["experience","test_score(out of 10)","interview_score(out of 10)"]],
                                                 df[["salary($)"]],train_size = .8,random_state = 43)

In [100]:
model.fit(x_train,y_train)

LinearRegression()

In [101]:
model.predict(x_test)

array([[61555.17368556],
       [78687.02811242]])

In [102]:
model.predict([[10,7.83,7]])

array([[75247.25136333]])

In [103]:
model.predict([[2,9,6]])

array([[52988.92791781]])

In [105]:
model.predict([[12,10,10]])

array([[89093.4523943]])

In [104]:
model.score(x_test,y_test)

0.8791935687621864

In [109]:
model.predict_proba([[12,10,10]])

AttributeError: 'LinearRegression' object has no attribute 'predictproba'

In [1]:
import joblib

In [2]:
joblib.dump("model","model_by_me")

['model_by_me']

In [6]:
mohit_vijay = joblib.load("model_joblib")

In [8]:
mohit_vijay.predict([[12,10,10]])

array([90510.46025105])