In [1]:
import pandas as pd 

In [2]:
# multinomoial mainly use for discreate and text data feature and bernauli use for binomial feature and gaussian use for 
#continues feature

In [3]:
df = pd.read_csv("spam_detector.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df["spam_column"]= df["Category"].map({"ham" : 0,"spam" : 1})

In [5]:
df.groupby("Category").describe()

spam_column                                   
               count mean  std  min  25%  50%  75%  max
Category                                               
ham           4825.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
spam           747.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

In [6]:
df.head()

Category                                            Message  spam_column
0      ham  Go until jurong point, crazy.. Available only ...            0
1      ham                      Ok lar... Joking wif u oni...            0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...            1
3      ham  U dun say so early hor... U c already then say...            0
4      ham  Nah I don't think he goes to usf, he lives aro...            0

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test = train_test_split(df["Message"],df["spam_column"],train_size = .6)

In [37]:
from sklearn.feature_extraction.text import CountVectorizer

In [38]:
text = CountVectorizer()

In [39]:
(type(x_train))

pandas.core.series.Series

In [40]:
x_new_train = text.fit_transform(x_train)  # it is use to convert values in numpy matrix

In [41]:
dir(text)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixe

In [42]:
x_new_train   # class 'numpy.int64' arra

<3343x6625 sparse matrix of type '<class 'numpy.int64'>'
	with 44346 stored elements in Compressed Sparse Row format>

In [43]:
x_new_train.toarray()[0:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [44]:
from sklearn.naive_bayes import MultinomialNB

In [45]:
model = MultinomialNB()

In [46]:
model.fit(x_new_train,y_train)

MultinomialNB()

In [21]:
#MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [47]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [48]:
email_transform = text.transform(emails)

In [24]:
print(type(email_transform))

<class 'scipy.sparse.csr.csr_matrix'>


In [25]:
model.predict(email_transform)

array([0, 1], dtype=int64)

In [26]:
x_test_new = text.transform(x_test.values)

In [27]:
model.score(x_test_new,y_test)

0.9869896814715119

In [28]:
from sklearn.pipeline import Pipeline

In [29]:
clf =Pipeline([("vectorizer",CountVectorizer()),("nb",MultinomialNB())])

In [30]:
# Pipeline(memory=None,
#      steps=[('vectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
#         dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
#         lowercase=True, max_df=1.0, max_features=None, min_df=1,
#         ngram_range=(1, 1), preprocessor=None, stop_words=None,
#         strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
#         tokenizer=None, vocabulary=None)), ('nb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])


In [31]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [32]:
clf.score(x_test,y_test)

0.9869896814715119

# exercise 

In [33]:
Machine Learning Tutorial - Naive Bayes: Exercise
Use wine dataset from sklearn.datasets to classify wines into 3 categories. Load the dataset and split
it into test and train. After that train the model using Gaussian and Multinominal classifier and post which model 
performs better. Use the trained model to perform some predictions on test data.

SyntaxError: invalid syntax (Temp/ipykernel_47208/1008045376.py, line 1)

In [ ]:
from sklearn.datasets import load_wine

In [ ]:
wine = load_wine()

In [ ]:
dir(wine)

In [ ]:
df = pd.DataFrame(wine.data,columns = wine.feature_names)

In [ ]:
df["target"] = wine.target

In [ ]:
df["target_name"] = df.target.apply(lambda x : wine.target_names[x])

In [ ]:
df.head()

In [ ]:
continuous dataset thats why gaussian is better than multinomoalnb

In [ ]:
df.corr()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt 

In [ ]:
plt.figure(figsize = (16,8))
sns.heatmap(df.corr(),annot =True)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(["target","target_name"],axis =1),df["target"],train_size = .7)

In [ ]:
from sklearn.naive_bayes import MultinomialNB,GaussianNB

In [ ]:
# continuous dataset thats why gaussian is better than multinomoalnb

In [ ]:
model_multi = MultinomialNB()
model_multi.fit(x_train,y_train)
model_multi.score(x_test,y_test)

In [ ]:
model_multi.predict(x_test)

In [ ]:
series = pd.Series(model_multi.predict(x_test))
series.head()

In [ ]:
t = series.apply(lambda x :wine.target_names[x])
t.head()

In [ ]:
model_gaussian = GaussianNB()
model_gaussian.fit(x_train,y_train)
model_gaussian.score(x_test,y_test)

In [ ]:
model_gaussian.predict(x_test)

In [ ]:
y_test

In [ ]:

from sklearn import datasets
wine = datasets.load_wine()
dir(wine)
['DESCR', 'data', 'feature_names', 'target', 'target_names']
wine.data[0:2]
array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03]])
wine.feature_names
['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']
wine.target_names
array(['class_0', 'class_1', 'class_2'], dtype='<U7')
wine.target[0:2]
array([0, 0])
import pandas as pd
df = pd.DataFrame(wine.data,columns=wine.feature_names)
df.head()
alcohol	malic_acid	ash	alcalinity_of_ash	magnesium	total_phenols	flavanoids	nonflavanoid_phenols	proanthocyanins	color_intensity	hue	od280/od315_of_diluted_wines	proline
0	14.23	1.71	2.43	15.6	127.0	2.80	3.06	0.28	2.29	5.64	1.04	3.92	1065.0
1	13.20	1.78	2.14	11.2	100.0	2.65	2.76	0.26	1.28	4.38	1.05	3.40	1050.0
2	13.16	2.36	2.67	18.6	101.0	2.80	3.24	0.30	2.81	5.68	1.03	3.17	1185.0
3	14.37	1.95	2.50	16.8	113.0	3.85	3.49	0.24	2.18	7.80	0.86	3.45	1480.0
4	13.24	2.59	2.87	21.0	118.0	2.80	2.69	0.39	1.82	4.32	1.04	2.93	735.0
df['target'] = wine.target
df[50:70]
alcohol	malic_acid	ash	alcalinity_of_ash	magnesium	total_phenols	flavanoids	nonflavanoid_phenols	proanthocyanins	color_intensity	hue	od280/od315_of_diluted_wines	proline	target
50	13.05	1.73	2.04	12.4	92.0	2.72	3.27	0.17	2.91	7.20	1.12	2.91	1150.0	0
51	13.83	1.65	2.60	17.2	94.0	2.45	2.99	0.22	2.29	5.60	1.24	3.37	1265.0	0
52	13.82	1.75	2.42	14.0	111.0	3.88	3.74	0.32	1.87	7.05	1.01	3.26	1190.0	0
53	13.77	1.90	2.68	17.1	115.0	3.00	2.79	0.39	1.68	6.30	1.13	2.93	1375.0	0
54	13.74	1.67	2.25	16.4	118.0	2.60	2.90	0.21	1.62	5.85	0.92	3.20	1060.0	0
55	13.56	1.73	2.46	20.5	116.0	2.96	2.78	0.20	2.45	6.25	0.98	3.03	1120.0	0
56	14.22	1.70	2.30	16.3	118.0	3.20	3.00	0.26	2.03	6.38	0.94	3.31	970.0	0
57	13.29	1.97	2.68	16.8	102.0	3.00	3.23	0.31	1.66	6.00	1.07	2.84	1270.0	0
58	13.72	1.43	2.50	16.7	108.0	3.40	3.67	0.19	2.04	6.80	0.89	2.87	1285.0	0
59	12.37	0.94	1.36	10.6	88.0	1.98	0.57	0.28	0.42	1.95	1.05	1.82	520.0	1
60	12.33	1.10	2.28	16.0	101.0	2.05	1.09	0.63	0.41	3.27	1.25	1.67	680.0	1
61	12.64	1.36	2.02	16.8	100.0	2.02	1.41	0.53	0.62	5.75	0.98	1.59	450.0	1
62	13.67	1.25	1.92	18.0	94.0	2.10	1.79	0.32	0.73	3.80	1.23	2.46	630.0	1
63	12.37	1.13	2.16	19.0	87.0	3.50	3.10	0.19	1.87	4.45	1.22	2.87	420.0	1
64	12.17	1.45	2.53	19.0	104.0	1.89	1.75	0.45	1.03	2.95	1.45	2.23	355.0	1
65	12.37	1.21	2.56	18.1	98.0	2.42	2.65	0.37	2.08	4.60	1.19	2.30	678.0	1
66	13.11	1.01	1.70	15.0	78.0	2.98	3.18	0.26	2.28	5.30	1.12	3.18	502.0	1
67	12.37	1.17	1.92	19.6	78.0	2.11	2.00	0.27	1.04	4.68	1.12	3.48	510.0	1
68	13.34	0.94	2.36	17.0	110.0	2.53	1.30	0.55	0.42	3.17	1.02	1.93	750.0	1
69	12.21	1.19	1.75	16.8	151.0	1.85	1.28	0.14	2.50	2.85	1.28	3.07	718.0	1
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.3, random_state=100)
from sklearn.naive_bayes import GaussianNB, MultinomialNB
model = GaussianNB()
model.fit(X_train,y_train)
GaussianNB(priors=None, var_smoothing=1e-09)
model.score(X_test,y_test)
1.0
mn = MultinomialNB()
mn.fit(X_train,y_train)
mn.score(X_test,y_test)
0.7777777777777778

In [ ]:


0.9827709978463748
Sklearn Pipeline

from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])
clf.fit(X_train, y_train)
Pipeline(memory=None,
     steps=[('vectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('nb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])
clf.score(X_test,y_test)
0.9827709978463748
clf.predict(emails)
array([0, 1], dtype=int64)